# Generated by Django 5.0.2 on 2024-02-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordenventa',
            name='nro_articulo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
