# Generated by Django 5.0.2 on 2024-02-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0003_alter_itemordenventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordenventa',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
