# Generated by Django 5.0.2 on 2024-03-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractos', '0001_initial'),
        ('ordenventa', '0015_ordendecompra_monto_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrosOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_correlativo', models.CharField(max_length=255)),
                ('fecha_emision_factura', models.DateField()),
                ('cliente_factura', models.CharField(max_length=255)),
                ('ruc_factura', models.CharField(max_length=11)),
                ('tipo_moneda', models.CharField(choices=[('soles', 'Soles'), ('dolares', 'Dólares')], max_length=7)),
                ('descripcion_factura', models.TextField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detraccion', models.DecimalField(decimal_places=2, help_text='Porcentaje de la detracción', max_digits=5)),
                ('neto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tipo_cobro_factura', models.CharField(choices=[('factoring', 'Factoring'), ('directo', 'Directo')], max_length=9)),
                ('dscto_factoring', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del descuento por factoring', max_digits=5)),
                ('extracto_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractos.extractosbancarios')),
                ('orden_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='ordenventa.ordenventa')),
            ],
        ),
    ]
