# Generated by Django 5.0.2 on 2024-03-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractos', '0001_initial'),
        ('ordenventa', '0018_facturaelectronica_orden_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='desc_factoring',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento Factoring (%)'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='extracto_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extractos.extractosbancarios', verbose_name='Extracto Bancario'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo_cobro',
            field=models.CharField(blank=True, choices=[('factoring', 'Factoring'), ('directo', 'Directo')], max_length=20, null=True, verbose_name='Tipo de Cobro'),
        ),
    ]
