# Generated by Django 5.0.2 on 2024-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0019_facturaelectronica_desc_factoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='tipo_pago',
            field=models.CharField(default='', max_length=50),
        ),
    ]
