# Generated by Django 5.0.2 on 2024-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_alter_articulo_en_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='en_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='grupo_articulos',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ultima_revalorizacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
