# Generated by Django 5.0.2 on 2024-02-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_dni', models.CharField(max_length=20, unique=True, verbose_name='RUC/DNI')),
                ('nombre_proveedor', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
                ('nombre_banco', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('moneda', models.CharField(choices=[('USD', 'Dólar Americano'), ('PEN', 'Sol Peruano')], default='PEN', max_length=10, verbose_name='Moneda')),
                ('nro_cuenta', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
