# Generated by Django 5.0.2 on 2024-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_proveedor_nro_cuenta_interbancario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.IntegerField(blank=True, choices=[(0, 'Soles'), (1, 'Dolares')], default=0, null=True, verbose_name='Moneda'),
        ),
    ]
