# Generated by Django 5.0.2 on 2024-02-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('igv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detraccion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('clase', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('numero_bancario', models.CharField(max_length=20)),
                ('cuotas', models.IntegerField()),
            ],
        ),
    ]
