# Generated by Django 5.0.2 on 2024-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(max_length=50)),
                ('orden_compra', models.CharField(max_length=50)),
                ('proyecto', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ruc_dni', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('monto_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
            ],
        ),
    ]
