# Generated by Django 5.0.2 on 2024-03-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0002_cronograma_doc_pagocronograma_pdf_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='entidad_bancaria',
            new_name='entidad',
        ),
    ]
