# Generated by Django 5.0.2 on 2024-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0003_rename_entidad_bancaria_cronograma_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocronograma',
            name='pdf_pago',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pagos_pdfs/'),
        ),
    ]
