# Generated by Django 5.0.2 on 2024-03-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0004_alter_pagocronograma_pdf_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('tiempo_aplazamiento', models.IntegerField(help_text='Tiempo de aplazamiento en meses')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago', models.CharField(max_length=10)),
                ('vencimiento', models.DateField()),
                ('amortizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='cronogramas.resolucion')),
            ],
        ),
    ]
