# Generated by Django 5.0.2 on 2024-03-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0005_resolucion_detallepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='resolucion',
            name='numero_resolucion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolucion',
            name='tipo_resolucion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='tiempo_aplazamiento',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.CharField(max_length=255)),
                ('vencimiento', models.DateField()),
                ('amortizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronogramas.resolucion')),
            ],
        ),
    ]
