# Generated by Django 5.0.2 on 2024-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0006_remove_resolucion_numero_remove_resolucion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='archivo_pdf',
            field=models.FileField(default=0, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
