# Generated by Django 5.0.2 on 2024-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0005_itemordenventa_desc_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='direccion_proyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenventa',
            name='observacion',
            field=models.CharField(max_length=255),
        ),
    ]
