# Generated by Django 5.0.2 on 2024-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0013_ordendecompra_monto_detraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_pagada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pagada'),
        ),
    ]
