# Generated by Django 5.0.2 on 2024-03-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0017_facturaelectronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenventa.ordenventa', verbose_name='Orden de Venta'),
            preserve_default=False,
        ),
    ]
