# Generated by Django 5.0.2 on 2024-03-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=100)),
                ('numero_cuenta_banco', models.CharField(max_length=100)),
                ('detalle_banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='extractosbancarios',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='extractosbancarios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='extractosbancarios',
            name='fecha_extracto',
        ),
        migrations.RemoveField(
            model_name='extractosbancarios',
            name='tipo_movimiento',
        ),
        migrations.AddField(
            model_name='extractosbancarios',
            name='fecha_operacion',
            field=models.DateField(null=True, verbose_name='Fecha de Operación'),
        ),
        migrations.AddField(
            model_name='extractosbancarios',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractosbancarios',
            name='itf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ITF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractosbancarios',
            name='numero_movimiento',
            field=models.CharField(default=0, max_length=50, verbose_name='Número de Movimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractosbancarios',
            name='referencia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractosbancarios',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extractos.banco', verbose_name='Banco'),
        ),
    ]
