# Generated by Django 5.0.2 on 2024-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_articulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('grupo_articulos', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('unidad_medida_inventario', models.CharField(blank=True, max_length=100)),
                ('ultimo_precio_revalorizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultimo_precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
