# Generated by Django 5.0.2 on 2024-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=100)),
                ('grupo_articulos', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('ultima_revalorizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='en_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
