# Generated by Django 5.0.2 on 2024-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0004_itemordenventa_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordenventa',
            name='desc_articulo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
