# Generated by Django 5.0.2 on 2024-02-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0007_ordendecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='banco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='clase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='cuotas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='numero_bancario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
