# Generated by Django 5.0.2 on 2024-02-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0008_ordendecompra_banco_ordendecompra_clase_and_more'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='numero_bancario',
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_de_compra', to='reportes.proveedor'),
        ),
    ]
