# Generated by Django 5.0.2 on 2024-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0014_ordendecompra_fecha_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
