# Generated by Django 5.0.2 on 2024-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenventa', '0020_ordendecompra_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='banco_relacionado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco Relacionado'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='numero_movimiento_bancario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Movimiento Bancario'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='restante_rendir',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Restante por Rendir'),
        ),
    ]
