# Generated by Django 5.0.2 on 2024-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nro_cuenta_interbancario',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número de Cuenta Interbancario'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.IntegerField(blank=True, choices=[(0, 'Soles'), (1, 'Dólares')], default=0, null=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_banco',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nro_cuenta',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ruc_dni',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='RUC/DNI'),
        ),
    ]
